### ISSUE TITLE
dagda check stuck on Analyzing

### ISSUE THREAD

**Issue by urand0m** [eliasgranderubio/dagda#35]
### Short description

check docker image stuck on "status": "Analyzing"

### Reproduction steps

python3 dagda.py start
python3 dagda.py check --docker_image [local_docker_image]
 

### Expected results

I expected that by analyzing the docker image would show the report but after 4 hours no show of any status.

### Actual results

Current status :

{
        "anomalies": 0,
        "image_name": "sonarqube",
        "libs_vulns": 0,
        "malware_bins": 0,
        "os_vulns": 0,
        "reportid": "5ba3520bd6ca3f0514fa2833",
        "start_date": "2018-09-20 07:53:47.924439",
        "status": "Analyzing"
    }

### On which platforms did you notice this:

running kali in docker with mongodb in docker communicating over exposed port. 

### Backtrace

```
<2018-09-20 09:11:47,364> <ERROR> <DagdaServer> <docker_events_monitor> <run:60> <Unexpected exception of type InvalidDocument occured: ("key 'io.github.offensive-security.license' must not contain '.'",)>
```

**Comment by eliasgranderubio** [comment]
Hi @urand0m ,

Sometimes, I have seen the execution takes 30 minutes until its completion but 4 hours is too much so, something was wrong in your analysis.

Please, update to the last Dagda version and start dagda server with the next command `python3 dagda.py start -d` because the backtrace atached to this issue shows an error fixed in a previous commit. After that, rerun your analysis and give me feedback about your errors.

Anyway, if there is not any functional issue, the performance bug would be fixed when issue #34 is closed, so if you want collaborate to fix it, all PR are welcome :-)

**Comment by eliasgranderubio** [comment]
I've just fixed the issue #34 and I've reviewed all Dagda features, and all of them work fine.

Please, check again your issue and let me know if it is not fixed with the last updates yet.

**Comment by eliasgranderubio** [comment]
Hi @urand0m 

Could you give me any feedback about this issue?

**Comment by eliasgranderubio** [comment]
I close this issue because I have not any feedback about it for a long time. 

Please, if the error persists, reopen it.

**Comment by moisesdelacruz301997** [comment]
Hi, I have the same issue. I think the error is still happening.

Check always displays a status of "Analyzing". 

Refer to below.

 {
        "id": "5de9f4690663cd0001eea729",
        "image_name": "mongo",
        "status": "Analyzing",
        "timestamp": "2019-12-06 06:25:45.539682"
    }
